spring.application.name=ticketing-api

# 0. Konfigurasi Server
server.port=8085

# 1. Koneksi Database (Support Docker Environment Variables)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/db_ticketing?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:dibimbing123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Konfigurasi JPA / Hibernate
# 'none' atau 'validate' (Flyway yang mengelola tabel)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# 3. Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.check-location=true
spring.flyway.baseline-on-migrate=true

# 4. Security JWT
application.security.jwt.secret-key=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000
